<a href="https://colab.research.google.com/github/Schota/shares/blob/master/Deep_Learning__artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

This one was for one of the keggle competition.

### Importing the libraries

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [ ]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('rawtrain.csv')
X = dataset.iloc[:, 4:8].values
y = dataset.iloc[:, 1].values

In [ ]:
testset = pd.read_csv('rawtest.csv')
X_test = testset.iloc[:, 3:7].values

In [ ]:
X

array([['male', 22.0, 1, 0],
       ['female', 38.0, 1, 0],
       ['female', 26.0, 0, 0],
       ...,
       ['female', nan, 1, 2],
       ['male', 26.0, 0, 0],
       ['male', 32.0, 0, 0]], dtype=object)

In [ ]:
X_test

array([['male', 34.5, 0, 0],
       ['female', 47.0, 1, 0],
       ['male', 62.0, 0, 0],
       ...,
       ['male', 38.5, 0, 0],
       ['male', nan, 0, 0],
       ['male', nan, 1, 1]], dtype=object)

In [ ]:
X[:, 1]

array([22.0, 38.0, 26.0, 35.0, 35.0, nan, 54.0, 2.0, 27.0, 14.0, 4.0,
       58.0, 20.0, 39.0, 14.0, 55.0, 2.0, nan, 31.0, nan, 35.0, 34.0,
       15.0, 28.0, 8.0, 38.0, nan, 19.0, nan, nan, 40.0, nan, nan, 66.0,
       28.0, 42.0, nan, 21.0, 18.0, 14.0, 40.0, 27.0, nan, 3.0, 19.0, nan,
       nan, nan, nan, 18.0, 7.0, 21.0, 49.0, 29.0, 65.0, nan, 21.0, 28.5,
       5.0, 11.0, 22.0, 38.0, 45.0, 4.0, nan, nan, 29.0, 19.0, 17.0, 26.0,
       32.0, 16.0, 21.0, 26.0, 32.0, 25.0, nan, nan, 0.83, 30.0, 22.0,
       29.0, nan, 28.0, 17.0, 33.0, 16.0, nan, 23.0, 24.0, 29.0, 20.0,
       46.0, 26.0, 59.0, nan, 71.0, 23.0, 34.0, 34.0, 28.0, nan, 21.0,
       33.0, 37.0, 28.0, 21.0, nan, 38.0, nan, 47.0, 14.5, 22.0, 20.0,
       17.0, 21.0, 70.5, 29.0, 24.0, 2.0, 21.0, nan, 32.5, 32.5, 54.0,
       12.0, nan, 24.0, nan, 45.0, 33.0, 20.0, 47.0, 29.0, 25.0, 23.0,
       19.0, 37.0, 16.0, 24.0, nan, 22.0, 24.0, 19.0, 18.0, 19.0, 27.0,
       9.0, 36.5, 42.0, 51.0, 22.0, 55.5, 40.5, nan, 51.0, 16.0, 

##Taking Care of Missing Data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:4])
X[:, 1:4] = imputer.transform(X[:, 1:4])

In [ ]:
X[:, 1]

array([22.0, 38.0, 26.0, 35.0, 35.0, 29.69911764705882, 54.0, 2.0, 27.0,
       14.0, 4.0, 58.0, 20.0, 39.0, 14.0, 55.0, 2.0, 29.69911764705882,
       31.0, 29.69911764705882, 35.0, 34.0, 15.0, 28.0, 8.0, 38.0,
       29.69911764705882, 19.0, 29.69911764705882, 29.69911764705882,
       40.0, 29.69911764705882, 29.69911764705882, 66.0, 28.0, 42.0,
       29.69911764705882, 21.0, 18.0, 14.0, 40.0, 27.0, 29.69911764705882,
       3.0, 19.0, 29.69911764705882, 29.69911764705882, 29.69911764705882,
       29.69911764705882, 18.0, 7.0, 21.0, 49.0, 29.0, 65.0,
       29.69911764705882, 21.0, 28.5, 5.0, 11.0, 22.0, 38.0, 45.0, 4.0,
       29.69911764705882, 29.69911764705882, 29.0, 19.0, 17.0, 26.0, 32.0,
       16.0, 21.0, 26.0, 32.0, 25.0, 29.69911764705882, 29.69911764705882,
       0.83, 30.0, 22.0, 29.0, 29.69911764705882, 28.0, 17.0, 33.0, 16.0,
       29.69911764705882, 23.0, 24.0, 29.0, 20.0, 46.0, 26.0, 59.0,
       29.69911764705882, 71.0, 23.0, 34.0, 34.0, 28.0, 29.69911764705882,

In [ ]:
from sklearn.impute import SimpleImputer
imputer_test = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer_test.fit(X_test[:, 1:4])
X_test[:, 1:4] = imputer_test.transform(X_test[:, 1:4])

### Encoding categorical data

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 0] = le.fit_transform(X[:, 0])

In [ ]:
X

array([[1, 22.0, 1.0, 0.0],
       [0, 38.0, 1.0, 0.0],
       [0, 26.0, 0.0, 0.0],
       ...,
       [0, 29.69911764705882, 1.0, 2.0],
       [1, 26.0, 0.0, 0.0],
       [1, 32.0, 0.0, 0.0]], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X_test[:, 0] = le.fit_transform(X_test[:, 0])

### Splitting the dataset into the Training set and Test set

In [ ]:
#from sklearn.model_selection import train_test_split
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
X_test = sc.transform(X_test)

In [ ]:
X_test

array([[ 0.73769513,  0.36944878, -0.4745452 , -0.47367361],
       [-1.35557354,  1.33137817,  0.43279337, -0.47367361],
       [ 0.73769513,  2.48569343, -0.4745452 , -0.47367361],
       ...,
       [ 0.73769513,  0.67726619, -0.4745452 , -0.47367361],
       [ 0.73769513,  0.04413122, -0.4745452 , -0.47367361],
       [ 0.73769513,  0.04413122,  0.43279337,  0.76762988]])

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=128, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X, y, batch_size= 32, epochs= 100)

Epoch 1/100
28/28 [==============================] - 0s 1ms/step - loss: 0.5598 - accuracy: 0.7767
Epoch 2/100
28/28 [==============================] - 0s 1ms/step - loss: 0.4819 - accuracy: 0.7991
Epoch 3/100
28/28 [==============================] - 0s 1ms/step - loss: 0.4720 - accuracy: 0.8070
Epoch 4/100
28/28 [==============================] - 0s 1ms/step - loss: 0.4696 - accuracy: 0.8227
Epoch 5/100
28/28 [==============================] - 0s 1ms/step - loss: 0.4640 - accuracy: 0.8193
Epoch 6/100
28/28 [==============================] - 0s 2ms/step - loss: 0.4620 - accuracy: 0.8215
Epoch 7/100
28/28 [==============================] - 0s 2ms/step - loss: 0.4628 - accuracy: 0.8215
Epoch 8/100
28/28 [==============================] - 0s 2ms/step - loss: 0.4570 - accuracy: 0.8204
Epoch 9/100
28/28 [==============================] - 0s 2ms/step - loss: 0.4595 - accuracy: 0.8227
Epoch 10/100
28/28 [==============================] - 0s 2ms/step - loss: 0.4572 - accuracy: 0.8159
Epoch 11/

In [ ]:
y

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

## Part 4 - Making the predictions

### Predicting the Test set results

In [ ]:
X_test

array([[ 0.73769513,  0.36944878, -0.4745452 , -0.47367361],
       [-1.35557354,  1.33137817,  0.43279337, -0.47367361],
       [ 0.73769513,  2.48569343, -0.4745452 , -0.47367361],
       ...,
       [ 0.73769513,  0.67726619, -0.4745452 , -0.47367361],
       [ 0.73769513,  0.04413122, -0.4745452 , -0.47367361],
       [ 0.73769513,  0.04413122,  0.43279337,  0.76762988]])

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1))))